## xdc file for BASYS 3 FPGA

	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
 
 set_property BITSTREAM.General.UnconstrainedPins {Allow} [current_design]
# Switches

#[3:0]loadA,[3:0]loadB,[3:0]loadC,[3:0]loadD,
#R2 TO V17

set_property PACKAGE_PIN V17 [get_ports {loadD[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadD[0]}]
set_property PACKAGE_PIN V16 [get_ports {loadD[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadD[1]}]
set_property PACKAGE_PIN W16 [get_ports {loadD[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadD[2]}]
set_property PACKAGE_PIN W17 [get_ports {loadD[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadD[3]}]
set_property PACKAGE_PIN W15 [get_ports {loadC[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadC[0]}]
set_property PACKAGE_PIN V15 [get_ports {loadC[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadC[1]}]
set_property PACKAGE_PIN W14 [get_ports {loadC[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadC[2]}]
set_property PACKAGE_PIN W13 [get_ports {loadC[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadC[3]}]
set_property PACKAGE_PIN V2 [get_ports {loadB[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadB[0]}]
set_property PACKAGE_PIN T3 [get_ports {loadB[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadB[1]}]
set_property PACKAGE_PIN T2 [get_ports {loadB[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadB[2]}]
set_property PACKAGE_PIN R3 [get_ports {loadB[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadB[3]}]
set_property PACKAGE_PIN W2 [get_ports {loadA[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadA[0]}]
set_property PACKAGE_PIN U1 [get_ports {loadA[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadA[1]}]
set_property PACKAGE_PIN T1 [get_ports {loadA[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadA[2]}]
set_property PACKAGE_PIN R2 [get_ports {loadA[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {loadA[3]}]
 
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {segment7[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[0]}]
set_property PACKAGE_PIN W6 [get_ports {segment7[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[1]}]
set_property PACKAGE_PIN U8 [get_ports {segment7[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[2]}]
set_property PACKAGE_PIN V8 [get_ports {segment7[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[3]}]
set_property PACKAGE_PIN U5 [get_ports {segment7[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[4]}]
set_property PACKAGE_PIN V5 [get_ports {segment7[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[5]}]
set_property PACKAGE_PIN U7 [get_ports {segment7[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segment7[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
#	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]


##Buttons
#set_property PACKAGE_PIN U18 [get_ports btnC]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnC]
#set_property PACKAGE_PIN T18 [get_ports btnU]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN W19 [get_ports ISW2]						
	set_property IOSTANDARD LVCMOS33 [get_ports ISW2]
set_property PACKAGE_PIN T17 [get_ports ISW1]						
	set_property IOSTANDARD LVCMOS33 [get_ports ISW1]
#set_property PACKAGE_PIN U17 [get_ports btnD]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnD]
